### ISSUE TITLE
blazing on windows 

### ISSUE THREAD

**Issue by happycze** [effkay/blazing#82]
Hi guys,
thank you for your effort, blazing seems to be on the right way to simplify deployment via git, but... i'm on windows 7 box:(

I ran into following problems when trying setup blazing:
- found typo in blazing.rb "autoload :COmmands", should be "autoload :Commands"?
- grit uses posix spawn, thus doesn't work on win because of wrong filepath parsing, workaround for repository.rb in grit_repository_object was to add Grit::Git.git_binary = 'c:\Program Files (x86)\Git\bin\git.exe'
-  generating post-receive hook doesn't work if "tmp" directory doesn't exists
- copying post-receive hook fails, because scp cannot resolve "/tmp/post-receive" file
- set_hook_permissions then fails of course...

I was trying to find something else, capistrano is little bit overengineered and forces me to use remote git repositories), so i was excited about blazing, but right now i'm sort of confused...

**Comment by effkay** [comment]
@happycze I personaly do not have any windows machine to work/test this on, and therefore I do not intend to add windows support myself. If you care to do a PR which fixes the issues you mention I'd consider merging it in of course though!
