### ISSUE TITLE
features: support for spring in development, and figaro support

### ISSUE THREAD

**Issue by u007** [effkay/blazing#89]
Hi,

i did a work around to fix spring issue by deleting all files in bin/*
and added shared support for temporary directory,
but im not sure if this is required, as we can add em into gitignore

but i did add in support for figaro, etc: config/application.yml
hope you can add in something that may be standardised, perhaps checking if spring gem n figaro is listed, and add additional tasks to run.

here is my deployment sample:

https://github.com/u007/blazing

to deploy:

```
    create to $HOME/rails/shared
    upload shared/config/application.yml (for figaro)
    mkdir shared/log
    mkdir shared/public/uploads
    mkdir shared/public/system
    mkdir shared/tmp
    mkdir shared/vendor/bundle
```

next, in your project,

```
    blazing init
    edit config/blazing.rb
    rake :"server:deploy"
    copy this file to lib/tasks/
    http://pastebin.com/13cTyvGg #if you use mod passenger
    blazing setup production
    # this will deploy git after deploy scripts on server
    blazing update production # to update later if changed blazing config
```

thanks for the great work :+1:

**Comment by effkay** [comment]
Hi @u007 

I had not heard about figaro so far. How do you Imagine blazing to integrate with it... could you elaborate on that?

Concerning spring, I don't understand where spring and blazing would fit together and what your use case is exactly?

**Comment by effkay** [comment]
closing since stale. Please get back in touch if this is still an issue.
