### ISSUE TITLE
bundle: command not found

### ISSUE THREAD

**Issue by u007** [effkay/blazing#90]
rails 4.2,
using rvm, ruby 2.3.1
```
remote: ------
remote: ------  [blazing] ENTERING POST RECEIVE HOOK FOR: production
remote: ------
remote: ------> [blazing] Doing a hard reset and checking out refs/heads/main since thats what you pushed
remote: HEAD is now at d455b93 return all roles
remote: Previous HEAD position was d455b93... return all roles
remote: HEAD is now at 3de87bf... fixed product added parent to category
remote: ------> [blazing] Bundling gems!!
remote: hooks/post-receive: line 28: bundle: command not found
remote: hooks/post-receive: line 38: syntax error near unexpected token `fi'
remote: hooks/post-receive: line 38: `fi'
```

**Comment by effkay** [comment]
Hi @u007 

It seems like you do not have bundler installed on your server. (see Usage -> Installation in Readme)

**Comment by u007** [comment]
ive never changed any setting.
it just stop working and im using rvm

**Comment by effkay** [comment]
Hi @u007 

Not sure why it would stop working. Maybe an rvm update/new gemset? Just make sure that the rvm environment your are running in has bundler installed and you should be fine!

**Comment by u007** [comment]
i made the fix! :)
i went into server ,
vi .git/hooks/post-receive 
change all command bundle ... to
```
rvm use 2.3.1 do bundle ...
```
and it works!
maybe u can put this in readme or something

**Comment by effkay** [comment]
Keep in mind that if you run `blazing update` your post-receive hook will be overwritten. The safe way to solve your problem would be to use the env_scripts options to source in rvm. Check out the [sample configuration file](https://github.com/effkay/blazing/blob/master/lib/blazing/templates/config.erb) for more details.

**Comment by u007** [comment]
ive already added env_scripts /etc/profile.d/rvm.sh
and even ran rvm use 2.3.1
didnt work
